### PR TITLE
Fix #29

### LINKED ISSUE #29: Show dimensions text sprite issue
When I checked `Show Tensor Dimensions` and `Show Conv Dimensions` in AlexNet style, the text sprite (width and height) is showing wrong place. The width and height texts seem to be exchanged each other in location. 

issue

### PR DESCRIPTION
**Pull request by alexlenail**

### CODE REVIEW

File: AlexNet.js [hunk 1]
```diff
@@ -195,12 +195,12 @@ function AlexNet() {
             if (showConvDims && index < architecture.length - 1) {
 
                 // Conv Dims
-                sprite = makeTextSprite(layer['filterWidth'].toString());
-                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( convFn(layer['filterWidth'])/2, -3, depthFn(layer['depth'])/2 ) );
+                sprite = makeTextSprite(layer['filterHeight'].toString());
+                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( convFn(layer['filterHeight'])/2, -3, depthFn(layer['depth'])/2 ) );
```
Comment (aFewThings) [inline AlexNet.js]: I think you need to change like this. Because `height` text should be placed to the right, it needs to use `width` size. 
```suggestion
                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( convFn(layer['filterWidth'])/2, -3, depthFn(layer['depth'])/2 ) );
```

File: AlexNet.js [hunk 2]
```diff
@@ -195,12 +195,12 @@ function AlexNet() {
...
                 sprites.add( sprite );
 
-                sprite = makeTextSprite(layer['filterHeight'].toString());
-                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( -1, convFn(layer['filterHeight'])/2, depthFn(layer['depth'])/2 ) );
+                sprite = makeTextSprite(layer['filterWidth'].toString());
+                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( -1, convFn(layer['filterWidth'])/2, depthFn(layer['depth'])/2 ) );
```
Comment (aFewThings) [inline AlexNet.js]: As same reason as above, this line should be changed like this.
```suggestion
                sprite.position.copy( conv_object.position ).sub( new THREE.Vector3( -1, convFn(layer['filterHeight'])/2, depthFn(layer['depth'])/2 ) );
```

**Review by aFewThings — CHANGES_REQUESTED** [review]
With this commits that changed `showConvDims` part on 195 line, you need to modify `showDims` part also :).

**Comment by alexlenail** [comment]
This seems to work, in my quick anecdotal testing.

**Comment by aFewThings** [comment]
It fixes conv dims, but still has issues in tensor dims. 
https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/AlexNet.js#L186
https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/AlexNet.js#L190
